services:
  db:
    image: postgres:15
    ports:
      - 5436:5432
    environment:
      POSTGRES_DB: seoks
      POSTGRES_USER: seoks
      POSTGRES_PASSWORD: seoks
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.keystone/postgres:/var/lib/postgresql/data

